pull_request_rules:
  - name: automatic merge for Dependabot pull requests & Scala Steward
    conditions:
        - or:
            - author~=^dependabot(|-preview)\[bot\]$
            - author=thanz
    actions:
      merge:
        method: merge
