pull_request_rules:
  - name: automatic merge for Dependabot pull requests & Scala Steward
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - author=thanhz
    actions:
      merge:
        method: merge
