name: printing details

on:
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  upsert-develop-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Print some details
    steps:
      - name: Printing details
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |  
              echo "The user who created the PR: ${{ github.event.pull_request.user.login }}"
              echo "PR is from branch ${{ github.event.pull_request.base.ref }}"
              echo "Name of Repository is ${{ github.repository }}"
