name: printing details

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  upsert-develop-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Print some details
    steps:
      - name: Printing details
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |  
              echo 'The user who created the PR:'
              echo ${{ github.event.pull_request.user.login }}
