name: Upsert `develop` branch

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  upsert-develop-branch:
    if: github.event.pull_request.user.login == 'scala-steward-thanhz[bot]'
    permissions: write-all
    runs-on: ubuntu-latest
    name: Create `develop` branch or rebase it to latest `main`
    steps:
      - name: Create `develop` branch (if it does not exists)
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |  
              echo 'The user who created the PR:'
              echo ${{ github.event.pull_request.user.login }}
